apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metalgrid-devplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: metalgrid-devplugin
  template:
    metadata:
      labels:
        app: metalgrid-devplugin
    spec:
      priorityClassName: system-node-critical
      containers:
        - name: devplugin
          image: metalgrid/devplugin:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: NUM_DEVICES
              value: "4"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
