---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metalgrid-operator
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metalgrid.dev
  resources:
  - acceleratorjobs
  - inferenceservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metalgrid.dev
  resources:
  - acceleratorjobs/finalizers
  verbs:
  - update
- apiGroups:
  - metalgrid.dev
  resources:
  - acceleratorjobs/status
  - inferenceservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metalgrid.dev
  resources:
  - acceleratorpools
  - quotapolicies
  verbs:
  - get
  - list
  - watch
