---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metalgrid-operator
  namespace: metalgrid-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metalgrid-apiserver
  namespace: metalgrid-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metalgrid-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metalgrid-operator
subjects:
  - kind: ServiceAccount
    name: metalgrid-operator
    namespace: metalgrid-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metalgrid-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metalgrid-apiserver
subjects:
  - kind: ServiceAccount
    name: metalgrid-apiserver
    namespace: metalgrid-system
