// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: jobs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJobRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Team             string                 `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Image            string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command          []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args             []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	AcceleratorType  string                 `protobuf:"bytes,5,opt,name=accelerator_type,json=acceleratorType,proto3" json:"accelerator_type,omitempty"`
	AcceleratorCount int32                  `protobuf:"varint,6,opt,name=accelerator_count,json=acceleratorCount,proto3" json:"accelerator_count,omitempty"`
	Priority         int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobRequest) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *CreateJobRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateJobRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CreateJobRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateJobRequest) GetAcceleratorType() string {
	if x != nil {
		return x.AcceleratorType
	}
	return ""
}

func (x *CreateJobRequest) GetAcceleratorCount() int32 {
	if x != nil {
		return x.AcceleratorCount
	}
	return 0
}

func (x *CreateJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateJobRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          string                 `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *ListJobsRequest) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *ListJobsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type DeleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobRequest) Reset() {
	*x = DeleteJobRequest{}
	mi := &file_jobs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRequest) ProtoMessage() {}

func (x *DeleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobResponse) Reset() {
	*x = DeleteJobResponse{}
	mi := &file_jobs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobResponse) ProtoMessage() {}

func (x *DeleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobResponse) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{5}
}

type GetCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityRequest) Reset() {
	*x = GetCapacityRequest{}
	mi := &file_jobs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest) ProtoMessage() {}

func (x *GetCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityRequest.ProtoReflect.Descriptor instead.
func (*GetCapacityRequest) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{6}
}

type Job struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Team             string                 `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Image            string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	AcceleratorType  string                 `protobuf:"bytes,4,opt,name=accelerator_type,json=acceleratorType,proto3" json:"accelerator_type,omitempty"`
	AcceleratorCount int32                  `protobuf:"varint,5,opt,name=accelerator_count,json=acceleratorCount,proto3" json:"accelerator_count,omitempty"`
	Priority         int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Message          string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_jobs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{7}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *Job) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Job) GetAcceleratorType() string {
	if x != nil {
		return x.AcceleratorType
	}
	return ""
}

func (x *Job) GetAcceleratorCount() int32 {
	if x != nil {
		return x.AcceleratorCount
	}
	return 0
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Job) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Capacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Available     int64                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_jobs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{8}
}

func (x *Capacity) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Capacity) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

var File_jobs_proto protoreflect.FileDescriptor

const file_jobs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"jobs.proto\x12\fmetalgrid.v1\"\x87\x02\n" +
	"\x10CreateJobRequest\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12)\n" +
	"\x10accelerator_type\x18\x05 \x01(\tR\x0facceleratorType\x12+\n" +
	"\x11accelerator_count\x18\x06 \x01(\x05R\x10acceleratorCount\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\"\x1f\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x0fListJobsRequest\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"Z\n" +
	"\x10ListJobsResponse\x12%\n" +
	"\x04jobs\x18\x01 \x03(\v2\x11.metalgrid.v1.JobR\x04jobs\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\"\n" +
	"\x10DeleteJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11DeleteJobResponse\"\x14\n" +
	"\x12GetCapacityRequest\"\x84\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04team\x18\x02 \x01(\tR\x04team\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12)\n" +
	"\x10accelerator_type\x18\x04 \x01(\tR\x0facceleratorType\x12+\n" +
	"\x11accelerator_count\x18\x05 \x01(\x05R\x10acceleratorCount\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\">\n" +
	"\bCapacity\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x03R\tavailable2\xe9\x02\n" +
	"\vJobsService\x12>\n" +
	"\tCreateJob\x12\x1e.metalgrid.v1.CreateJobRequest\x1a\x11.metalgrid.v1.Job\x128\n" +
	"\x06GetJob\x12\x1b.metalgrid.v1.GetJobRequest\x1a\x11.metalgrid.v1.Job\x12I\n" +
	"\bListJobs\x12\x1d.metalgrid.v1.ListJobsRequest\x1a\x1e.metalgrid.v1.ListJobsResponse\x12L\n" +
	"\tDeleteJob\x12\x1e.metalgrid.v1.DeleteJobRequest\x1a\x1f.metalgrid.v1.DeleteJobResponse\x12G\n" +
	"\vGetCapacity\x12 .metalgrid.v1.GetCapacityRequest\x1a\x16.metalgrid.v1.CapacityB@Z>github.com/jahnavi-yelamanchi/metalgrid/internal/grpcapi/pb;pbb\x06proto3"

var (
	file_jobs_proto_rawDescOnce sync.Once
	file_jobs_proto_rawDescData []byte
)

func file_jobs_proto_rawDescGZIP() []byte {
	file_jobs_proto_rawDescOnce.Do(func() {
		file_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)))
	})
	return file_jobs_proto_rawDescData
}

var file_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_jobs_proto_goTypes = []any{
	(*CreateJobRequest)(nil),   // 0: metalgrid.v1.CreateJobRequest
	(*GetJobRequest)(nil),      // 1: metalgrid.v1.GetJobRequest
	(*ListJobsRequest)(nil),    // 2: metalgrid.v1.ListJobsRequest
	(*ListJobsResponse)(nil),   // 3: metalgrid.v1.ListJobsResponse
	(*DeleteJobRequest)(nil),   // 4: metalgrid.v1.DeleteJobRequest
	(*DeleteJobResponse)(nil),  // 5: metalgrid.v1.DeleteJobResponse
	(*GetCapacityRequest)(nil), // 6: metalgrid.v1.GetCapacityRequest
	(*Job)(nil),                // 7: metalgrid.v1.Job
	(*Capacity)(nil),           // 8: metalgrid.v1.Capacity
}
var file_jobs_proto_depIdxs = []int32{
	7, // 0: metalgrid.v1.ListJobsResponse.jobs:type_name -> metalgrid.v1.Job
	0, // 1: metalgrid.v1.JobsService.CreateJob:input_type -> metalgrid.v1.CreateJobRequest
	1, // 2: metalgrid.v1.JobsService.GetJob:input_type -> metalgrid.v1.GetJobRequest
	2, // 3: metalgrid.v1.JobsService.ListJobs:input_type -> metalgrid.v1.ListJobsRequest
	4, // 4: metalgrid.v1.JobsService.DeleteJob:input_type -> metalgrid.v1.DeleteJobRequest
	6, // 5: metalgrid.v1.JobsService.GetCapacity:input_type -> metalgrid.v1.GetCapacityRequest
	7, // 6: metalgrid.v1.JobsService.CreateJob:output_type -> metalgrid.v1.Job
	7, // 7: metalgrid.v1.JobsService.GetJob:output_type -> metalgrid.v1.Job
	3, // 8: metalgrid.v1.JobsService.ListJobs:output_type -> metalgrid.v1.ListJobsResponse
	5, // 9: metalgrid.v1.JobsService.DeleteJob:output_type -> metalgrid.v1.DeleteJobResponse
	8, // 10: metalgrid.v1.JobsService.GetCapacity:output_type -> metalgrid.v1.Capacity
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jobs_proto_init() }
func file_jobs_proto_init() {
	if File_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobs_proto_goTypes,
		DependencyIndexes: file_jobs_proto_depIdxs,
		MessageInfos:      file_jobs_proto_msgTypes,
	}.Build()
	File_jobs_proto = out.File
	file_jobs_proto_goTypes = nil
	file_jobs_proto_depIdxs = nil
}
